sass/styles/objects/o-card-layout/card.scss

Revert "Scaling homepage"

---

public/index.html
sass/styles/elements/elements.home.search.scss
sass/styles/elements/elements.navigation.scss
sass/styles/generic/reset.scss
sass/styles/objects/o-homepage-layout/o-homepage.scss

- Placed Search box in nav-bar

Search-Box

---

public/overview.html
sass/styles/objects/o-overview-course/o-overview-course.scss

Overview course s

---

public/index.html

add: js for carousel

---

public/courses.html

Signed-off-by: Bhavya Aggarwal <bhavyaaggarwal1209@gmail.com>

Fix courses page markup

---

public/all-courses.html

Signed-off-by: Bhavya Aggarwal <bhavyaaggarwal1209@gmail.com>

All-Courses page

---

public/timeline.html
sass/styles/objects/o-content/o-timeline.scss

Signed-off-by: Bhavya Aggarwal <bhavyaaggarwal1209@gmail.com>

Add icons in timeline

---

public/about-accordian.html
sass/styles/_objects.scss
sass/styles/elements/elements.headings.scss
sass/styles/objects/o-about-course/o-accordian.scss
sass/styles/objects/o-accordian-layout/o-accordian-layout.scss
sass/styles/objects/o-content/o-timeline.scss

added accordian- about course

---

public/about-course.html
sass/styles/_objects.scss
sass/styles/elements/elements.headings.scss
sass/styles/objects/o-about-course/o-about-course.scss

added course summary

---

public/buy-top.html
sass/styles/objects/o-about-course/o-buy-top.scss

scaled buy-top sticky card

---

public/buy-right.html
sass/styles/objects/o-about-course/o-buy-right.scss

Buy right s

---

public/about-course.html
public/buy-right.html
sass/styles/objects/o-about-course/o-about-course.scss
sass/styles/objects/o-about-course/o-buy-right.scss
sass/styles/objects/o-mycourse-layout/o-mycourse.scss

About course s

---

public/index.html
sass/styles/media-query/media.home.scss

center aligned home-img

---

public/about-course.html
public/buy-right.html
sass/styles/objects/o-about-course/o-buy-right.scss

added iframe to buy-right

---

public/index.html
sass/styles/_objects.scss
sass/styles/objects/o-footer/o-footer.scss

add: footer

---

public/overview.html
sass/styles/objects/o-overview-recent/o-overview-recent.scss

Signed-off-by: Bhavya Aggarwal <bhavyaaggarwal1209@gmail.com>

Fix overview cards size

---

public/otp-enroll.html
sass/styles/_objects.scss
sass/styles/objects/o-otp-enroll/o-otp-enroll.scss
sass/styles/settings/settings.color.scss

Otp enroll input

---

public/about-course.html
public/buy-right.html
public/buy-top.html
sass/styles/objects/o-about-course/o-buy-right.scss
sass/styles/objects/o-about-course/o-buy-top.scss
sass/styles/settings/settings.global.scss

Otp button

---

public/overview.html
sass/styles/_media-query.scss
sass/styles/elements/elements.status-circle.scss
sass/styles/media-query/media.course-progress.scss
sass/styles/objects/o-accordian-layout/o-accordian-layout.scss
sass/styles/objects/o-classroom-layout/o-classroom-layout.scss
sass/styles/objects/o-overview-container/o-overview-container.scss
sass/styles/settings/settings.font.scss

Course progress phone

---

public/overview.html
sass/styles/_media-query.scss
sass/styles/media-query/media.about-instructor.scss
sass/styles/media-query/media.course-progress/media.overview-course.scss
sass/styles/media-query/media.headings.scss
sass/styles/media-query/media.home.scss
sass/styles/objects/o-about-instructors/o-about-instructors.scss

About instructor

---

public/doc.html
sass/styles/elements/elements.home.search.scss

@abhishek97 @witty123 See the markup changes :)

Otp enroll css

---

sass/styles/objects/o-content/o-pb-submissions.scss

submission css fix

---

examples/views/checkout-card.hbs
sass/styles/_media-query.scss
sass/styles/_objects.scss
sass/styles/elements/elements.navigation.scss
sass/styles/media-query/media.checkout-card.scss
sass/styles/media-query/media.headings.scss
sass/styles/objects/o-checkout-card/o-checkout-card.scss

added dukaan checkout card

---

sass/styles/media-query/media.o-otp-enroll.scss

fix the padding of ENROLL TO COURSES VIA OTP section

---

examples/views/address-card.hbs
sass/styles/_media-query.scss
sass/styles/_objects.scss
sass/styles/media-query/media.address-card.scss
sass/styles/media-query/media.card.layout.scss
sass/styles/objects/o-address-card/o-address-card.scss

@witty123 @abhishek97 @aayusharora

added dukaan address card

---

examples/views/index.hbs
sass/styles/_elements.scss
sass/styles/elements/elements.pagination.scss

fixes #170 
@Prajjwal please review.

added pagination

---

sass/styles/media-query/media.content-section.scss

center align speedster for mobile

---

examples/views/doubts.hbs
sass/styles/objects/o-doubt/o-doubt.scss

in reference to https://github.com/coding-blocks/codingblocks.online.projectx/issues/109
@witty123 please check

fix overflow in doubts section

---

sass/styles/elements/elements.level.scss
sass/styles/objects/o-card-layout/card.scss

#127  
Usage example -
```
<div class="difficulty-div">
<div class="{{course.difficultyName}}-level"></div>
<div class="{{course.difficultyName}}-text">
{{uppercase course.difficultyName}}
</div>
</div>
```

align center difficulty icon

---

examples/views/add-client.hbs
examples/views/client-page.hbs
sass/styles/_media-query.scss
sass/styles/_objects.scss
sass/styles/media-query/media.o-client-add.scss
sass/styles/media-query/media.o-client-page.scss
sass/styles/objects/o-client-add/o-client-add.scss
sass/styles/objects/o-client-page/o-client-page.scss
sass/styles/objects/o-side-nav/o-side-nav.scss

Client pages

---

examples/views/add-address.hbs
examples/views/add-client.hbs
examples/views/app-page.hbs
examples/views/profile-page-edit.hbs
examples/views/profile-page.hbs
sass/styles/_media-query.scss
sass/styles/_objects.scss
sass/styles/media-query/media.o-add-address.scss
sass/styles/media-query/media.o-profile.card.edit.scss
sass/styles/media-query/media.o-profile.card.scss
sass/styles/objects/o-add-address/o-add-address.scss
sass/styles/objects/o-app-page/o-app-page.scss
sass/styles/objects/o-client-add/o-client-add.scss
sass/styles/objects/o-profile-page-edit/o-profile-page-edit.scss
sass/styles/objects/o-profile-page/o-profile-page.scss

Add Address page

---

examples/views/changedp.hbs
sass/styles/_media-query.scss
sass/styles/_objects.scss
sass/styles/media-query/media.changdp.scss
sass/styles/objects/o-changedp/o-changedp.scss
sass/styles/objects/o-modal/o-modal.scss

added changedp modal

---

sass/styles/elements/elements.navigation.scss

Fixes #187.
Pinging @vdvibhu20

Fix overflowing navbar.

---

sass/styles/elements/elements.navigation.scss

Reverts coding-blocks/motley#214

Revert "Fix overflowing navbar."

---

sass/styles/objects/o-nav-layout/o-nav-layout.scss

https://github.com/coding-blocks/oneauth/issues/256
@championswimmer

 top right photo improvements

---

examples/views/about-course.hbs
sass/styles/_media-query.scss
sass/styles/media-query/media.course-review.scss
sass/styles/objects/course-rating/o-rating-stats.scss
sass/styles/objects/o-about-course/o-about-course.scss
sass/styles/settings/settings.font.scss

Review section

---

sass/styles/objects/o-skeleton/o-skeleton-card.scss

Parent issue and PR
https://github.com/coding-blocks/codingblocks.online.projectx/pull/228

skeleton card resize

---

sass/styles/objects/o-notification/o-notification.scss

https://github.com/coding-blocks/codingblocks.online.projectx/issues/224
@championswimmer

adjusted padding on notifications

---

examples/views/announcements.hbs
sass/styles/media-query/media.course-progress/media.course-progress.scss
sass/styles/objects/o-classroom-layout/o-classroom-layout.scss

https://github.com/coding-blocks/codingblocks.online.projectx/pull/244 @witty123

buy button and free trial changes

---

sass/styles/_components.scss

Feedback modal fix

---

sass/styles/objects/buttons.scss

@vdvibhu20 
@abhishek97 
Pls review.

Add: button-solid disabled

---

examples/views/referral-code.hbs
sass/styles/_components.scss
sass/styles/_media-query.scss
sass/styles/components/referral-code/referral-code.scss
sass/styles/media-query/media.referral-code.scss

add referral code ui

---

sass/styles/objects/accordian.scss

Font for video duration

---

examples/views/index.hbs
sass/styles/components/home-card/home-card.scss
sass/styles/media-query/media.home-card.scss

Add: difficulty dots to home cards

---

sass/styles/components/about-course/accordian.scss
sass/styles/objects/accordian.scss

@abhishek97 
@vdvibhu20 
review karlo.

Video Duration Changes

---

examples/components/certificate-locked.hbs
examples/components/certificate.hbs
examples/views/overview.hbs
sass/styles/components/certificate/certificate.scss

add certificate component locked state

---

examples/views/list.hbs
sass/styles/_elements.scss
sass/styles/_objects.scss
sass/styles/_tools.scss
sass/styles/elements/input.scss
sass/styles/elements/ul-li.scss
sass/styles/objects/list.scss
sass/styles/settings/settings.color.scss
sass/styles/tools/list.scss

added lists

---

sass/styles/components/add-address/add-address.scss
sass/styles/components/address-page/address-page.scss
sass/styles/components/arrangement/arrangement.scss
sass/styles/components/client-page/client-page.scss
sass/styles/elements/input.scss

Oneauth button and input field fixes

---

examples/components/doubts.hbs
examples/views/ask-doubts.hbs
sass/styles/components/doubts/doubts.scss

add feedback card for doubts

---

.travis.yml
README.md

fix travis build

---

examples/views/code-editor.hbs
examples/views/index.hbs
sass/styles/_components.scss
sass/styles/components/code-editor.scss
sass/styles/objects/border-card.scss
sass/styles/objects/img-card.scss
sass/styles/settings/settings.color.scss

Code Editor for HackerBlocks v2 complete.

Code Editor

---

examples/components/cb-navbar.hbs
examples/views/hb-landing.hbs
examples/views/index.hbs
sass/styles/_components.scss
sass/styles/components/cb-navbar/index.scss

add cb-navbar
